# Generated by Django 5.2.7 on 2025-11-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafego', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linha',
            name='classificacao',
            field=models.CharField(blank=True, choices=[('RD', 'Radial'), ('DM', '<span data-i18n="route.metrics.transverse">Diametral</span>'), ('CR', 'Circular'), ('TR', '<span data-i18n="route.metrics.trunk">Troncal</span>'), ('AL', '<span data-i18n="route.metrics.feeder">Alimentadora</span>'), ('IT', '<span data-i18n="route.metrics.intersectoral">Intersetorial</span>'), ('ES', '<span data-i18n="route.metrics.special">Especial</span>')], max_length=3),
        ),
    ]
