# Generated by Django 4.2.4 on 2023-12-15 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('trafego', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embarque', models.DateTimeField()),
                ('referencia', models.DateField()),
                ('veiculo', models.CharField(blank=True, max_length=30)),
                ('cartao', models.CharField(blank=True, max_length=60)),
                ('aplicacao', models.CharField(blank=True, max_length=60)),
                ('tipo', models.CharField(blank=True, max_length=60)),
                ('tarifa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.empresa')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='trafego.linha')),
            ],
        ),
    ]
