# Generated by Django 4.2.4 on 2023-10-27 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trafego', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linha',
            name='garagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='local_garagem', to='trafego.localidade'),
        ),
    ]
