# Generated by Django 4.2.4 on 2023-12-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafego', '0002_passageiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='passageiro',
            name='dia_tipo',
            field=models.CharField(blank=True, choices=[('U', 'Util'), ('S', 'Sabado'), ('D', 'Domingo'), ('F', 'Ferias'), ('E', 'Especial')], default='U', max_length=3),
        ),
    ]
