# Generated by Django 4.2.4 on 2023-10-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafego', '0005_linha_demanda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='sentido',
            field=models.CharField(blank=True, choices=[('I', 'Ida'), ('V', 'Volta')], default='1', max_length=3),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='tipo',
            field=models.CharField(blank=True, choices=[('1', '1 Produtiva'), ('2', '2 Expresso'), ('3', '3 Semi Expresso'), ('4', '4 Extra'), ('5', '5 Acesso'), ('6', '6 Recolhe'), ('7', '7 Intervalo'), ('9', '9 Reservado')], default='1', max_length=3),
        ),
    ]
