# Generated by Django 4.2.4 on 2023-10-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafego', '0007_viagem_encerrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='escalas',
            field=models.TextField(blank=True),
        ),
    ]
