# Generated by Django 6.0.2 on 2026-02-28 10:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('atividades', models.TextField(blank=True, verbose_name='Atividades')),
                ('funcoes_fixas', models.JSONField(blank=True, default=list, verbose_name='Funções Fixas')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EventoFrequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('rastreio', models.SlugField(blank=True, unique=True, verbose_name='Rastreio')),
                ('categoria', models.CharField(choices=[('PRD', 'Jornada/Trabalho'), ('INT', 'Intervalo'), ('AJ', 'Ausência Justificada'), ('ANJ', 'Ausência Não Justificada'), ('FLG', 'Folga'), ('HE', 'Hora Extra')], default='PRD', max_length=4, verbose_name='Categoria')),
                ('contabiliza_horas', models.BooleanField(default=True, verbose_name='Contabiliza Horas')),
                ('remunerado', models.BooleanField(default=True, verbose_name='Remunerado')),
                ('dia_inteiro', models.BooleanField(default=False, verbose_name='Dia Inteiro')),
                ('desconta_efetivos', models.BooleanField(default=False, verbose_name='Desconta dias efetivos')),
                ('prioridade', models.PositiveIntegerField(default=1, verbose_name='Prioridade')),
                ('cor', models.CharField(blank=True, max_length=7, null=True, verbose_name='Cor Hex')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='MotivoReajuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True, verbose_name='Nome')),
                ('dias_ciclo', models.PositiveIntegerField(default=0, verbose_name='Dias Ciclo')),
                ('inicio', models.DateField(default=datetime.datetime.today, verbose_name='Inicio')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime', models.CharField(blank=True, choices=[('CLT', 'CLT'), ('PJ', 'Pessoa Jurídica'), ('EST', 'Estágio'), ('AP', 'Aprendiz')], default='CLT', max_length=5, verbose_name='Regime')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário')),
                ('inicio', models.DateField(default=datetime.datetime.today, verbose_name='Inicio')),
                ('fim', models.DateField(blank=True, null=True, verbose_name='Fim')),
                ('carga_mensal', models.PositiveIntegerField(default=220, verbose_name='Carga Mensal')),
                ('carga_diaria', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='C Diária Decimal')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='pessoal.cargo', verbose_name='Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, db_index=True, null=True, verbose_name='Data')),
                ('inicio', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Início')),
                ('fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('metadados', models.JSONField(blank=True, default=dict, help_text='Armazena os horários vindos da FrequenciaImport antes da edição', verbose_name='Importação')),
                ('editado', models.BooleanField(default=False, verbose_name='Editado Manualmente')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='pessoal.contrato')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.eventofrequencia', verbose_name='Evento')),
            ],
            options={
                'ordering': ['inicio'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('apelido', models.CharField(blank=True, max_length=20, verbose_name='Apelido')),
                ('nome_social', models.CharField(blank=True, max_length=100, verbose_name='Nome Social')),
                ('genero', models.CharField(blank=True, choices=[('N', 'Não informado'), ('M', 'Masculino'), ('F', 'Feminino')], max_length=3, verbose_name='Gênero')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data Nascimento')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='Rg')),
                ('rg_emissao', models.DateField(blank=True, null=True, verbose_name='Rg Emissão')),
                ('rg_orgao_expedidor', models.CharField(blank=True, max_length=15, verbose_name='Rg Org Expedidor')),
                ('cpf', models.CharField(blank=True, max_length=20, verbose_name='Cpf')),
                ('titulo_eleitor', models.CharField(blank=True, max_length=20, verbose_name='Titulo Eleitor')),
                ('titulo_zona', models.CharField(blank=True, max_length=10, verbose_name='Zona')),
                ('titulo_secao', models.CharField(blank=True, max_length=8, verbose_name='Seção')),
                ('reservista', models.CharField(blank=True, max_length=20, verbose_name='Reservista')),
                ('cnh', models.CharField(blank=True, max_length=20, verbose_name='Cnh')),
                ('cnh_categoria', models.CharField(blank=True, choices=[('', '----'), ('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('C', 'C'), ('AC', 'AC'), ('D', 'D'), ('AD', 'AD'), ('E', 'E'), ('AE', 'AE'), ('ACC', 'ACC')], max_length=4, verbose_name='Categoria')),
                ('cnh_primeira_habilitacao', models.DateField(blank=True, null=True, verbose_name='Primeira Habilitação')),
                ('cnh_emissao', models.DateField(blank=True, null=True, verbose_name='Emissão')),
                ('cnh_validade', models.DateField(blank=True, null=True, verbose_name='Validade')),
                ('fone1', models.CharField(blank=True, max_length=20, verbose_name='Fone 1')),
                ('fone2', models.CharField(blank=True, max_length=20, verbose_name='Fone 2')),
                ('email', models.CharField(blank=True, max_length=150, verbose_name='Email')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=60, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=5, verbose_name='Uf')),
                ('estado_civil', models.CharField(blank=True, choices=[('S', 'Solteiro'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viuvo')], max_length=3, verbose_name='Estado Civil')),
                ('nome_mae', models.CharField(blank=True, max_length=150, verbose_name='Nome da Mãe')),
                ('nome_pai', models.CharField(blank=True, max_length=150, verbose_name='Nome do Pai')),
                ('detalhe', models.TextField(blank=True, verbose_name='Detalhe')),
                ('matricula', models.CharField(max_length=15, unique=True, verbose_name='Matricula')),
                ('data_admissao', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Data Admissão')),
                ('data_desligamento', models.DateField(blank=True, null=True, verbose_name='Data Desligamento')),
                ('motivo_desligamento', models.CharField(blank=True, choices=[('EM', 'Pelo Empregador'), ('JC', 'Por Justa Causa'), ('PD', 'Pedido de Desligamento'), ('RI', 'Rescisão Indireta'), ('AB', 'Abandono de Emprego'), ('DJ', 'Decisão Judicial')], max_length=3, verbose_name='Motivo Desligamento')),
                ('pne', models.BooleanField(default=False, verbose_name='Pne')),
                ('foto', models.ImageField(blank=True, upload_to='pessoal/fotos/', verbose_name='Foto')),
                ('status', models.CharField(blank=True, choices=[('A', 'Ativo'), ('F', 'Afastado'), ('D', 'Desligado')], db_index=True, default='A', max_length=3, verbose_name='Status')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.filial', verbose_name='Filial')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=230, verbose_name='Nome')),
                ('parentesco', models.CharField(blank=True, choices=[('C', 'Cônjuge'), ('F', 'Filho / Enteado'), ('I', 'Irmão'), ('P', 'Pai / Mãe'), ('S', 'Sogro / Sogra'), ('A', 'Ascendente'), ('N', 'Descendente'), ('In', 'Incapaz'), ('M', 'Outro')], default='F', max_length=3, verbose_name='Parentesco')),
                ('genero', models.CharField(blank=True, choices=[('N', 'Não informado'), ('M', 'Masculino'), ('F', 'Feminino')], max_length=3, verbose_name='Gênero')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data Nascimento')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='Rg')),
                ('rg_emissao', models.DateField(blank=True, null=True, verbose_name='Rg Emissão')),
                ('rg_orgao_expedidor', models.CharField(blank=True, max_length=15, verbose_name='Rg Org Expedidor')),
                ('cpf', models.CharField(blank=True, max_length=20, verbose_name='Cpf')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.funcionario', verbose_name='Funcionário')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='pessoal.funcionario', verbose_name='Funcionário'),
        ),
        migrations.CreateModel(
            name='Afastamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, choices=[('D', 'Doenca'), ('A', 'Acidente Trabalho'), ('O', 'Outro')], default='D', max_length=3, verbose_name='Motivo')),
                ('origem', models.CharField(blank=True, choices=[('I', 'INSS'), ('E', 'Escala'), ('S', 'Sindicato'), ('G', 'Gestora'), ('O', 'Outro')], default='I', max_length=3, verbose_name='Origem')),
                ('data_afastamento', models.DateField(blank=True, default=datetime.datetime.today, null=True, verbose_name='Data Afastamento')),
                ('data_retorno', models.DateField(blank=True, null=True, verbose_name='Data Retorno')),
                ('reabilitado', models.BooleanField(default=False, verbose_name='Reabilitado')),
                ('remunerado', models.BooleanField(default=False, verbose_name='Remunerado')),
                ('detalhe', models.TextField(blank=True, verbose_name='Detalhe')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.funcionario', verbose_name='Funcionário')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('rastreio', models.SlugField(unique=True)),
                ('tipo', models.CharField(choices=[('P', 'Provento'), ('D', 'Desconto'), ('R', 'Referência')], default='P', max_length=3, verbose_name='Tipo')),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pessoal.grupoevento', verbose_name='Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='EventoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(default=datetime.datetime.today, verbose_name='Inicio')),
                ('fim', models.DateField(blank=True, null=True, verbose_name='Fim')),
                ('valor', models.TextField(blank=True, verbose_name='Valor')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.evento', verbose_name='Evento')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.funcionario', verbose_name='Funcionário')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.motivoreajuste', verbose_name='Motivo')),
            ],
        ),
        migrations.CreateModel(
            name='EventoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(default=datetime.datetime.today, verbose_name='Inicio')),
                ('fim', models.DateField(blank=True, null=True, verbose_name='Fim')),
                ('valor', models.TextField(blank=True, verbose_name='Valor')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.evento', verbose_name='Evento')),
                ('filiais', models.ManyToManyField(related_name='eventos_filial', to='core.filial', verbose_name='Filiais')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.motivoreajuste', verbose_name='Motivo')),
            ],
        ),
        migrations.CreateModel(
            name='EventoCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(default=datetime.datetime.today, verbose_name='Inicio')),
                ('fim', models.DateField(blank=True, null=True, verbose_name='Fim')),
                ('valor', models.TextField(blank=True, verbose_name='Valor')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.cargo', verbose_name='Cargo')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.evento', verbose_name='Evento')),
                ('filiais', models.ManyToManyField(related_name='eventos_cargo', to='core.filial', verbose_name='Filiais')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.motivoreajuste', verbose_name='Motivo')),
            ],
        ),
        migrations.CreateModel(
            name='PessoalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_config', models.JSONField(db_column='config', default=dict)),
                ('filial', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='pessoal_settings', to='core.filial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessamentoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CF', 'Consolidação de Frequência'), ('FP', 'Folha de Pagamento'), ('CE', 'Carga de Escala')], max_length=2, verbose_name='Tipo')),
                ('competencia', models.DateField(db_index=True, verbose_name='Competência')),
                ('status', models.CharField(choices=[('AG', 'Aguardando'), ('PR', 'Processando'), ('OK', 'Concluído'), ('ER', 'Erro')], db_index=True, default='AG', max_length=2, verbose_name='Status')),
                ('iniciado_em', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('resultado', models.JSONField(blank=True, default=dict, verbose_name='Resultado')),
                ('observacoes', models.JSONField(blank=True, default=list, verbose_name='Observações')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filial', verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'Job de Processamento',
                'ordering': ['-concluido_em'],
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoal.setor', verbose_name='Setor'),
        ),
        migrations.CreateModel(
            name='TurnoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao_ciclo', models.IntegerField(verbose_name='Posição Ciclo')),
                ('horarios', models.JSONField(default=list, verbose_name='Horários')),
                ('tolerancia', models.PositiveIntegerField(default=10, verbose_name='Tolerância')),
                ('eh_folga', models.BooleanField(default=False, verbose_name='É Folga')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='pessoal.turno', verbose_name='Turno')),
            ],
            options={
                'ordering': ['posicao_ciclo'],
            },
        ),
        migrations.CreateModel(
            name='TurnoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_vigencia', models.DateField(default=datetime.datetime.today, verbose_name='Inicio Vigência')),
                ('fim_vigencia', models.DateField(blank=True, null=True, verbose_name='Fim Vigência')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_turnos', to='pessoal.contrato', verbose_name='Contrato')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoal.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Histórico Turno',
                'verbose_name_plural': 'Históricos Turnos',
                'ordering': ['-inicio_vigencia'],
            },
        ),
        migrations.CreateModel(
            name='FolhaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(db_index=True, verbose_name='Competência')),
                ('proventos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Proventos')),
                ('descontos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Descontos')),
                ('liquido', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Líquido')),
                ('regras', models.JSONField(default=dict, verbose_name='Regras')),
                ('erros', models.JSONField(blank=True, null=True, verbose_name='Erros')),
                ('total_erros', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Qtde Erros')),
                ('status', models.CharField(choices=[('R', 'Rascunho'), ('F', 'Fechado'), ('P', 'Pago'), ('C', 'Cancelado')], db_index=True, default='R', max_length=2, verbose_name='Status')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folhas', to='pessoal.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Folha de Pagamento',
                'verbose_name_plural': 'Folhas de Pagamento',
                'ordering': ['-competencia', 'contrato__funcionario__matricula'],
                'permissions': [('folha_dashboard', 'Can view folha dashboard')],
                'unique_together': {('contrato', 'competencia')},
            },
        ),
        migrations.CreateModel(
            name='FrequenciaConsolidada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(db_index=True, verbose_name='Competência')),
                ('inicio', models.DateTimeField(db_index=True, verbose_name='Início')),
                ('fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('status', models.CharField(choices=[('A', 'Aberto'), ('F', 'Fechado'), ('P', 'Processado')], default='A', max_length=1, verbose_name='Status')),
                ('bloqueado', models.BooleanField(default=False, verbose_name='Bloqueado')),
                ('processamento', models.DateTimeField(blank=True, null=True, verbose_name='Data Processamento')),
                ('consolidado', models.JSONField(blank=True, default=dict, verbose_name='Valores Consolidados')),
                ('erros', models.JSONField(blank=True, default=dict, verbose_name='Logs de Erros')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidados_freq', to='pessoal.contrato')),
            ],
            options={
                'unique_together': {('contrato', 'competencia')},
            },
        ),
        migrations.CreateModel(
            name='FrequenciaImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(db_index=True, verbose_name='Data e Hora Original')),
                ('origem', models.CharField(choices=[('AFD', 'Arquivo AFD (Relógio Físico)'), ('APP', 'Aplicativo Móvel (GPS)'), ('WEB', 'Portal do Funcionário'), ('CSV', 'Importação de Planilha')], default='AFD', max_length=3, verbose_name='Origem')),
                ('nsr', models.CharField(blank=True, help_text='Número Sequencial de Registro (AFD)', max_length=50, null=True, verbose_name='NSR')),
                ('num_relogio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Relógio/Equipamento')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('hash_verificacao', models.CharField(blank=True, help_text='Hash de integridade do registro original', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batidas_brutas', to='pessoal.contrato')),
            ],
            options={
                'verbose_name': 'Importação de Frequência',
                'verbose_name_plural': 'Importações de Frequências',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['contrato', 'data_hora'], name='pessoal_fre_contrat_f9b50e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['funcionario', 'inicio', 'fim'], name='idx_contrato_vigencia'),
        ),
        migrations.AddIndex(
            model_name='eventofuncionario',
            index=models.Index(fields=['funcionario', 'inicio', 'fim'], name='idx_ev_func_vigencia'),
        ),
        migrations.AddIndex(
            model_name='eventoempresa',
            index=models.Index(fields=['inicio', 'fim'], name='idx_ev_emp_vigencia'),
        ),
        migrations.AddIndex(
            model_name='eventocargo',
            index=models.Index(fields=['cargo', 'inicio', 'fim'], name='idx_ev_cargo_vigencia'),
        ),
        migrations.AlterUniqueTogether(
            name='processamentojob',
            unique_together={('tipo', 'filial', 'competencia')},
        ),
        migrations.AddConstraint(
            model_name='turnodia',
            constraint=models.UniqueConstraint(fields=('turno', 'posicao_ciclo'), name='unique_posicao_por_turno'),
        ),
    ]
