# Generated by Django 5.2.7 on 2025-11-25 09:24

import core.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('atividades', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='GrupoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotivoReajuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuncaoFixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('M', '<span data-i18n="personal.common.driver">Motorista</span>'), ('A', '<span data-i18n="personal.common.assistant">Auxiliar</span>'), ('T', '<span data-i18n="personal.common.traffic">Trafego</span>'), ('O', '<span data-i18n="personal.common.mechanics">Oficina</span>')], max_length=3, unique=True)),
                ('cargos', models.ManyToManyField(related_name='ffixas', to='pessoal.cargo')),
            ],
            options={
                'permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('apelido', models.CharField(blank=True, max_length=20)),
                ('nome_social', models.CharField(blank=True, max_length=100)),
                ('sexo', models.CharField(blank=True, choices=[('N', '<span data-i18n="compound.notInformed">Nao informado</span>'), ('M', '<span data-i18n="common.male">Masculino</span>'), ('F', '<span data-i18n="common.female">Feminino</span>')], max_length=3)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('rg', models.CharField(blank=True, max_length=20)),
                ('rg_emissao', models.DateField(blank=True, null=True)),
                ('rg_orgao_expedidor', models.CharField(blank=True, max_length=15)),
                ('cpf', models.CharField(blank=True, max_length=20)),
                ('titulo_eleitor', models.CharField(blank=True, max_length=20)),
                ('titulo_zona', models.CharField(blank=True, max_length=10)),
                ('titulo_secao', models.CharField(blank=True, max_length=8)),
                ('reservista', models.CharField(blank=True, max_length=20)),
                ('cnh', models.CharField(blank=True, max_length=20)),
                ('cnh_categoria', models.CharField(blank=True, choices=[('', '----'), ('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('C', 'C'), ('AC', 'AC'), ('D', 'D'), ('AD', 'AD'), ('E', 'E'), ('AE', 'AE'), ('ACC', 'ACC')], max_length=4)),
                ('cnh_primeira_habilitacao', models.DateField(blank=True, null=True)),
                ('cnh_emissao', models.DateField(blank=True, null=True)),
                ('cnh_validade', models.DateField(blank=True, null=True)),
                ('fone1', models.CharField(blank=True, max_length=20)),
                ('fone2', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=150)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=60)),
                ('uf', models.CharField(blank=True, max_length=5)),
                ('estado_civil', models.CharField(blank=True, choices=[('S', '<span data-i18n="common.single">Solteiro</span>'), ('C', '<span data-i18n="common.married">Casado</span>'), ('D', '<span data-i18n="common.divorced">Divorciado</span>'), ('V', '<span data-i18n="common.widower">Viuvo</span>')], max_length=3)),
                ('nome_mae', models.CharField(blank=True, max_length=150)),
                ('nome_pai', models.CharField(blank=True, max_length=150)),
                ('detalhe', models.TextField(blank=True)),
                ('matricula', models.CharField(max_length=15, unique=True)),
                ('regime', models.CharField(blank=True, choices=[('CLT', 'CLT'), ('PJ', '<span data-i18n="personal.employee.form.legalEntity">Pessoa Juridica</span>'), ('AP', '<span data-i18n="personal.common.apprentice">Aprendiz</span>')], default='CLT', max_length=5)),
                ('data_admissao', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('data_desligamento', models.DateField(blank=True, null=True)),
                ('motivo_desligamento', models.CharField(blank=True, choices=[('EM', '<span data-i18n="personal.common.dismissed">Pelo Empregador</span>'), ('JC', '<span data-i18n="personal.employee.form.forJustCause">Por Justa Causa</span>'), ('PD', '<span data-i18n="personal.common.resign">Pedido de Desligamento</span>'), ('RI', '<span data-i18n="personal.employee.form.indirectTermination">Rescisao Indireta</span>'), ('AB', '<span data-i18n="personal.employee.form.abandonment">Abandono de Emprego</span>'), ('DJ', '<span data-i18n="personal.employee.form.judicialTermination">Descisao Judicial</span>')], max_length=3)),
                ('pne', models.BooleanField(default=False)),
                ('foto', core.models.ImageField(blank=True, upload_to='pessoal/fotos/')),
                ('status', models.CharField(blank=True, choices=[('A', '<span data-i18n="common.active">Ativo</span>'), ('F', '<span data-i18n="personal.common.onLeave">Afastado</span>'), ('D', '<span data-i18n="personal.common.terminated">Desligado</span>')], default='A', max_length=3)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='pessoal.cargo')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.empresa')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('associar_usuario', 'Pode associar usuario a funcionário'), ('afastar_funcionario', 'Pode afastar funcionário'), ('desligar_funcionario', 'Pode desligar funcionário'), ('dashboard_funcionario', 'Pode acessar dashboard pessoal')],
            },
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=230)),
                ('parentesco', models.CharField(blank=True, choices=[('C', '<span data-i18n="personal.common.spouse">Conjuge</span>'), ('F', '<span data-i18n="personal.employee.form.sonStepson">Filho / Enteado</span>'), ('I', '<span data-i18n="personal.common.brother">Irmao</span>'), ('P', '<span data-i18n="personal.employee.form.fatherMother">Pai / Mae</span>'), ('S', '<span data-i18n="personal.common.fatherMotherInLaw">Sogro / Sogra</span>'), ('A', '<span data-i18n="personal.common.ascendant">Ascendente</span>'), ('N', '<span data-i18n="personal.common.descendant">Descendente</span>'), ('In', '<span data-i18n="personal.common.incapable">Incapaz</span>'), ('M', '<span data-i18n="common.other">Outro</span>')], default='F', max_length=3)),
                ('sexo', models.CharField(blank=True, choices=[('N', '<span data-i18n="compound.notInformed">Nao informado</span>'), ('M', '<span data-i18n="common.male">Masculino</span>'), ('F', '<span data-i18n="common.female">Feminino</span>')], max_length=3)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('rg', models.CharField(blank=True, max_length=20)),
                ('rg_emissao', models.DateField(blank=True, null=True)),
                ('rg_orgao_expedidor', models.CharField(blank=True, max_length=15)),
                ('cpf', models.CharField(blank=True, max_length=20)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Afastamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, choices=[('D', '<span data-i18n="personal.common.illness">Doenca</span>'), ('A', '<span data-i18n="personal.employee.form.workplaceAccident">Acidente Trabalho</span>'), ('O', '<span data-i18n="common.other">Outro</span>')], default='D', max_length=3)),
                ('origem', models.CharField(blank=True, choices=[('I', 'INSS'), ('E', '<span data-i18n="personal.common.schedule">Escala</span>'), ('S', '<span data-i18n="personal.common.syndicate">Sindicato</span>'), ('G', '<span data-i18n="common.regulator">Gestora</span>'), ('O', '<span data-i18n="common.other">Outro</span>')], default='I', max_length=3)),
                ('data_afastamento', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('data_retorno', models.DateField(blank=True, null=True)),
                ('reabilitado', models.BooleanField(default=False)),
                ('remunerado', models.BooleanField(default=False)),
                ('detalhe', models.TextField(blank=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('rastreio', models.CharField(max_length=40, unique=True)),
                ('tipo', models.CharField(choices=[('P', '<span data-i18n="personal.common.profit">Provento</span>'), ('D', '<span data-i18n="personal.common.deduction">Desconto</span>'), ('R', '<span data-i18n="personal.common.reference">Referencia</span>')], default='P', max_length=3)),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pessoal.grupoevento')),
            ],
        ),
        migrations.CreateModel(
            name='EventoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(default=datetime.datetime.today)),
                ('fim', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('V', '<span data-i18n="common.value">Valor</span>'), ('F', '<span data-i18n="common.formula">Formula</span>')], default='V', max_length=3)),
                ('valor', models.CharField(blank=True, max_length=250)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.evento')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.funcionario')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.motivoreajuste')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventoCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(default=datetime.datetime.today)),
                ('fim', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('V', '<span data-i18n="common.value">Valor</span>'), ('F', '<span data-i18n="common.formula">Formula</span>')], default='V', max_length=3)),
                ('valor', models.CharField(blank=True, max_length=250)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.cargo')),
                ('empresas', models.ManyToManyField(related_name='eventos_cargo', to='core.empresa')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.evento')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.motivoreajuste')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoal.setor'),
        ),
    ]
