# Generated by Django 6.0.2 on 2026-02-14 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnodia',
            name='entrada',
        ),
        migrations.RemoveField(
            model_name='turnodia',
            name='saida',
        ),
        migrations.AddField(
            model_name='turnodia',
            name='horarios',
            field=models.JSONField(default=dict, verbose_name='Horários'),
        ),
        migrations.AlterField(
            model_name='eventofrequencia',
            name='categoria',
            field=models.CharField(choices=[('PRD', 'Jornada/Trabalho'), ('INT', 'Intervalo'), ('AJ', 'Ausência Justificada'), ('ANJ', 'Ausência Não Justificada'), ('FLG', 'Folga'), ('HE', 'Hora Extra')], default='PRD', max_length=4, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Data Admissão'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='motivo_desligamento',
            field=models.CharField(blank=True, choices=[('EM', 'Pelo Empregador'), ('JC', 'Por Justa Causa'), ('PD', 'Pedido de Desligamento'), ('RI', 'Rescisão Indireta'), ('AB', 'Abandono de Emprego'), ('DJ', 'Decisão Judicial')], max_length=3, verbose_name='Motivo Desligamento'),
        ),
    ]
