# Generated by Django 5.2.7 on 2026-01-31 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pessoal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependente',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pessoal.grupoevento', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('P', 'Provento'), ('D', 'Desconto'), ('R', 'Referência')], default='P', max_length=3, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='eventocargo',
            name='filiais',
            field=models.ManyToManyField(related_name='eventos_cargo', to='core.filial', verbose_name='Filiais'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Ativo'), ('F', 'Afastado'), ('D', 'Desligado')], db_index=True, default='A', max_length=3, verbose_name='Status'),
        ),
    ]
