# Generated by Django 6.0.2 on 2026-03-04 14:22

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequenciaimport',
            options={'ordering': ['-data_hora'], 'verbose_name': 'Importacao de Frequencia', 'verbose_name_plural': 'Importacoes de Frequencias'},
        ),
        migrations.AlterModelOptions(
            name='turnohistorico',
            options={'ordering': ['-inicio_vigencia'], 'verbose_name': 'Historico Turno', 'verbose_name_plural': 'Historicos Turnos'},
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='data_desligamento',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='motivo_desligamento',
        ),
        migrations.AlterField(
            model_name='afastamento',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.funcionario', verbose_name='Funcionario'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='funcoes_fixas',
            field=models.JSONField(blank=True, default=list, verbose_name='Funcoes Fixas'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='carga_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Carga Diaria'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='pessoal.funcionario', verbose_name='Funcionario'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='regime',
            field=models.CharField(blank=True, choices=[('CLT', 'CLT'), ('PJ', 'Pessoa Juridica'), ('EST', 'Estagio'), ('AP', 'Aprendiz')], default='CLT', max_length=5, verbose_name='Regime'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.funcionario', verbose_name='Funcionario'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='genero',
            field=models.CharField(blank=True, choices=[('N', 'Não informado'), ('M', 'Masculino'), ('F', 'Feminino')], max_length=3, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='parentesco',
            field=models.CharField(blank=True, choices=[('C', 'Conjuge'), ('F', 'Filho / Enteado'), ('I', 'Irmao'), ('P', 'Pai / Mae'), ('S', 'Sogro / Sogra'), ('A', 'Ascendente'), ('N', 'Descendente'), ('In', 'Incapaz'), ('M', 'Outro')], default='F', max_length=3, verbose_name='Parentesco'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='rg_emissao',
            field=models.DateField(blank=True, null=True, verbose_name='Rg Emissao'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('P', 'Provento'), ('D', 'Desconto'), ('R', 'Referencia')], default='P', max_length=3, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='eventofrequencia',
            name='categoria',
            field=models.CharField(choices=[('PRD', 'Jornada/Trabalho'), ('INT', 'Intervalo'), ('AJ', 'Ausencia Justificada'), ('ANJ', 'Ausencia Nao Justificada'), ('FLG', 'Folga'), ('HE', 'Hora Extra')], default='PRD', max_length=4, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='eventofuncionario',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.funcionario', verbose_name='Funcionario'),
        ),
        migrations.AlterField(
            model_name='folhapagamento',
            name='competencia',
            field=models.DateField(db_index=True, verbose_name='Competencia'),
        ),
        migrations.AlterField(
            model_name='folhapagamento',
            name='liquido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Liquido'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='inicio',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='metadados',
            field=models.JSONField(blank=True, default=dict, verbose_name='Importacao'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Observacao'),
        ),
        migrations.AlterField(
            model_name='frequenciaconsolidada',
            name='competencia',
            field=models.DateField(db_index=True, verbose_name='Competencia'),
        ),
        migrations.AlterField(
            model_name='frequenciaconsolidada',
            name='inicio',
            field=models.DateTimeField(db_index=True, verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='frequenciaimport',
            name='nsr',
            field=models.CharField(blank=True, help_text='Numero Sequencial de Registro (AFD)', max_length=50, null=True, verbose_name='NSR'),
        ),
        migrations.AlterField(
            model_name='frequenciaimport',
            name='num_relogio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nr Relogio/Equipamento'),
        ),
        migrations.AlterField(
            model_name='frequenciaimport',
            name='origem',
            field=models.CharField(choices=[('AFD', 'Arquivo AFD (Relogio Fisico)'), ('APP', 'Aplicativo Movel (GPS)'), ('WEB', 'Portal do Funcionario'), ('CSV', 'Importacao de Planilha')], default='AFD', max_length=3, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cnh_emissao',
            field=models.DateField(blank=True, null=True, verbose_name='Emissao'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cnh_primeira_habilitacao',
            field=models.DateField(blank=True, null=True, verbose_name='Primeira Habilitacao'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Data Admissao'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereco'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='genero',
            field=models.CharField(blank=True, choices=[('N', 'Não informado'), ('M', 'Masculino'), ('F', 'Feminino')], max_length=3, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome da Mae'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='rg_emissao',
            field=models.DateField(blank=True, null=True, verbose_name='Rg Emissao'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='titulo_secao',
            field=models.CharField(blank=True, max_length=8, verbose_name='Secao'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='processamentojob',
            name='competencia',
            field=models.DateField(db_index=True, verbose_name='Competencia'),
        ),
        migrations.AlterField(
            model_name='processamentojob',
            name='concluido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Concluido em'),
        ),
        migrations.AlterField(
            model_name='processamentojob',
            name='historico',
            field=models.JSONField(blank=True, default=list, verbose_name='Historico'),
        ),
        migrations.AlterField(
            model_name='processamentojob',
            name='observacoes',
            field=models.JSONField(blank=True, default=list, verbose_name='Observacoes'),
        ),
        migrations.AlterField(
            model_name='processamentojob',
            name='status',
            field=models.CharField(choices=[('AG', 'Aguardando'), ('PR', 'Processando'), ('OK', 'Concluido'), ('ER', 'Erro')], db_index=True, default='AG', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='processamentojob',
            name='tipo',
            field=models.CharField(choices=[('CF', 'Consolidacao de Frequencia'), ('FF', 'Fechamento de Frequencia'), ('FP', 'Folha de Pagamento'), ('FH', 'Fechamento de Folha'), ('PF', 'Pagamento de Folha'), ('XF', 'Cancelamento de Folha'), ('CE', 'Carga de Escala')], max_length=2, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='turnodia',
            name='eh_folga',
            field=models.BooleanField(default=False, verbose_name='E Folga'),
        ),
        migrations.AlterField(
            model_name='turnodia',
            name='horarios',
            field=models.JSONField(default=list, verbose_name='Horarios'),
        ),
        migrations.AlterField(
            model_name='turnodia',
            name='posicao_ciclo',
            field=models.IntegerField(verbose_name='Posicao Ciclo'),
        ),
        migrations.AlterField(
            model_name='turnodia',
            name='tolerancia',
            field=models.PositiveIntegerField(default=10, verbose_name='Tolerancia'),
        ),
        migrations.AlterField(
            model_name='turnohistorico',
            name='fim_vigencia',
            field=models.DateField(blank=True, null=True, verbose_name='Fim Vigencia'),
        ),
        migrations.AlterField(
            model_name='turnohistorico',
            name='inicio_vigencia',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Inicio Vigencia'),
        ),
        migrations.CreateModel(
            name='Rescisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('EM', 'Pelo Empregador'), ('JC', 'Por Justa Causa'), ('PD', 'Pedido de Desligamento'), ('RI', 'Rescisao Indireta'), ('AB', 'Abandono de Emprego'), ('DJ', 'Decisao Judicial')], max_length=3, verbose_name='Motivo')),
                ('data_desligamento', models.DateField(verbose_name='Data de Desligamento')),
                ('aviso_tipo', models.CharField(blank=True, choices=[('T', 'Trabalhado'), ('I', 'Indenizado'), ('D', 'Dispensado')], max_length=1, verbose_name='Tipo de Aviso')),
                ('aviso_dias_devidos', models.PositiveSmallIntegerField(default=0, verbose_name='Dias Devidos')),
                ('aviso_dias_cumpridos', models.PositiveSmallIntegerField(default=0, verbose_name='Dias Cumpridos')),
                ('multa_fgts_paga', models.BooleanField(default=False, verbose_name='Multa FGTS Paga')),
                ('ferias_proporcionais_pagas', models.BooleanField(default=False, verbose_name='Ferias Proporcionais Pagas')),
                ('ferias_vencidas_pagas', models.BooleanField(default=False, verbose_name='Ferias Vencidas Pagas')),
                ('decimo_terceiro_proporcional', models.BooleanField(default=False, verbose_name='13 Proporcional Pago')),
                ('detalhe', models.TextField(blank=True, verbose_name='Detalhe')),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='rescisao', to='pessoal.contrato', verbose_name='Contrato rescindido')),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='rescisao', to='pessoal.funcionario', verbose_name='Funcionario')),
            ],
        ),
    ]
