# Generated by Django 6.0.2 on 2026-02-16 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pessoal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoalsettings',
            name='config',
            field=models.JSONField(db_column='config', default=dict),
        ),
        migrations.RenameField(
            model_name='pessoalsettings',
            old_name='config',
            new_name='_config',
        ),
        migrations.AlterField(
            model_name='pessoalsettings',
            name='filial',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='core.filial'),
        ),
    ]
