# Generated by Django 5.2.7 on 2025-11-13 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcaofixa',
            options={'permissions': []},
        ),
    ]
