# Generated by Django 5.2.7 on 2025-11-15 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pessoal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocargo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.empresa'),
        ),
    ]
