# Generated by Django 5.2.7 on 2026-01-18 10:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('dias_ciclo', models.PositiveIntegerField(default=7)),
                ('inicio', models.DateField(default=datetime.datetime.today)),
            ],
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='regime',
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime', models.CharField(blank=True, choices=[('CLT', 'CLT'), ('PJ', 'Pessoa Juridica'), ('EST', 'Estagio'), ('AP', 'Aprendiz')], default='CLT', max_length=5)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inicio', models.DateField(default=datetime.datetime.today)),
                ('fim', models.DateField(blank=True, null=True)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='pessoal.cargo')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='pessoal.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='TurnoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_vigencia', models.DateField(default=datetime.datetime.today)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_turnos', to='pessoal.contrato')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoal.turno')),
            ],
        ),
        migrations.CreateModel(
            name='TurnoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao_ciclo', models.IntegerField()),
                ('entrada', models.TimeField()),
                ('saida', models.TimeField()),
                ('carga_horaria', models.DurationField()),
                ('tolerancia', models.PositiveIntegerField(default=10)),
                ('eh_folga', models.BooleanField(default=False)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='pessoal.turno')),
            ],
            options={
                'ordering': ['posicao_ciclo'],
                'constraints': [models.UniqueConstraint(fields=('turno', 'posicao_ciclo'), name='unique_posicao_por_turno')],
            },
        ),
    ]
