# Generated by Django 5.2.7 on 2025-12-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_filial_nome_fantasia_alter_filial_empresa'),
        ('pessoal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventocargo',
            old_name='empresas',
            new_name='filiais',
        ),
        migrations.RemoveField(
            model_name='eventoempresa',
            name='empresas',
        ),
        migrations.AddField(
            model_name='eventoempresa',
            name='filiais',
            field=models.ManyToManyField(related_name='eventos_filial', to='core.filial'),
        ),
    ]
