# Generated by Django 5.2.7 on 2026-01-24 17:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_empresa_options_alter_empresa_cnpj_base_and_more'),
        ('pessoal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependente',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='sexo',
        ),
        migrations.AddField(
            model_name='dependente',
            name='genero',
            field=models.CharField(blank=True, choices=[('N', 'Não informado'), ('M', 'Masculino'), ('F', 'Feminino')], max_length=3, verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='genero',
            field=models.CharField(blank=True, choices=[('N', 'Não informado'), ('M', 'Masculino'), ('F', 'Feminino')], max_length=3, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='afastamento',
            name='data_afastamento',
            field=models.DateField(blank=True, default=datetime.datetime.today, null=True, verbose_name='Data Afastamento'),
        ),
        migrations.AlterField(
            model_name='afastamento',
            name='data_retorno',
            field=models.DateField(blank=True, null=True, verbose_name='Data Retorno'),
        ),
        migrations.AlterField(
            model_name='afastamento',
            name='detalhe',
            field=models.TextField(blank=True, verbose_name='Detalhe'),
        ),
        migrations.AlterField(
            model_name='afastamento',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='afastamento',
            name='motivo',
            field=models.CharField(blank=True, choices=[('D', 'Doenca'), ('A', 'Acidente Trabalho'), ('O', 'Outro')], default='D', max_length=3, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='afastamento',
            name='origem',
            field=models.CharField(blank=True, choices=[('I', 'INSS'), ('E', 'Escala'), ('S', 'Sindicato'), ('G', 'Gestora'), ('O', 'Outro')], default='I', max_length=3, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='afastamento',
            name='reabilitado',
            field=models.BooleanField(default=False, verbose_name='Reabilitado'),
        ),
        migrations.AlterField(
            model_name='afastamento',
            name='remunerado',
            field=models.BooleanField(default=False, verbose_name='Remunerado'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='atividades',
            field=models.TextField(blank=True, verbose_name='Atividades'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='funcoes_fixas',
            field=models.JSONField(blank=True, default=list, verbose_name='Funções Fixas'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nome',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoal.setor', verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='pessoal.cargo', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fim',
            field=models.DateField(blank=True, null=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='pessoal.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='inicio',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='regime',
            field=models.CharField(blank=True, choices=[('CLT', 'CLT'), ('PJ', 'Pessoa Jurídica'), ('EST', 'Estágio'), ('AP', 'Aprendiz')], default='CLT', max_length=5, verbose_name='Regime'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cpf'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data Nascimento'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='nome',
            field=models.CharField(max_length=230, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='parentesco',
            field=models.CharField(blank=True, choices=[('C', 'Cônjuge'), ('F', 'Filho / Enteado'), ('I', 'Irmão'), ('P', 'Pai / Mãe'), ('S', 'Sogro / Sogra'), ('A', 'Ascendente'), ('N', 'Descendente'), ('In', 'Incapaz'), ('M', 'Outro')], default='F', max_length=3, verbose_name='Parentesco'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='rg',
            field=models.CharField(blank=True, max_length=20, verbose_name='Rg'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='rg_emissao',
            field=models.DateField(blank=True, null=True, verbose_name='Rg Emissão'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='rg_orgao_expedidor',
            field=models.CharField(blank=True, max_length=15, verbose_name='Rg Org Expedidor'),
        ),
        migrations.AlterField(
            model_name='eventocargo',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.cargo', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='eventocargo',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.evento', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='eventocargo',
            name='filiais',
            field=models.ManyToManyField(related_name='eventos_cargo', to='core.empresa', verbose_name='Filiais'),
        ),
        migrations.AlterField(
            model_name='eventocargo',
            name='fim',
            field=models.DateField(blank=True, null=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='eventocargo',
            name='inicio',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='eventocargo',
            name='motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.motivoreajuste', verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='eventocargo',
            name='tipo',
            field=models.CharField(choices=[('V', 'Valor'), ('F', 'Fórmula')], default='V', max_length=3, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='eventocargo',
            name='valor',
            field=models.TextField(blank=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='eventoempresa',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.evento', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='eventoempresa',
            name='filiais',
            field=models.ManyToManyField(related_name='eventos_filial', to='core.filial', verbose_name='Filiais'),
        ),
        migrations.AlterField(
            model_name='eventoempresa',
            name='fim',
            field=models.DateField(blank=True, null=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='eventoempresa',
            name='inicio',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='eventoempresa',
            name='motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.motivoreajuste', verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='eventoempresa',
            name='tipo',
            field=models.CharField(choices=[('V', 'Valor'), ('F', 'Fórmula')], default='V', max_length=3, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='eventoempresa',
            name='valor',
            field=models.TextField(blank=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='eventofuncionario',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.evento', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='eventofuncionario',
            name='fim',
            field=models.DateField(blank=True, null=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='eventofuncionario',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='eventofuncionario',
            name='inicio',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='eventofuncionario',
            name='motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.motivoreajuste', verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='eventofuncionario',
            name='tipo',
            field=models.CharField(choices=[('V', 'Valor'), ('F', 'Fórmula')], default='V', max_length=3, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='eventofuncionario',
            name='valor',
            field=models.TextField(blank=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='apelido',
            field=models.CharField(blank=True, max_length=20, verbose_name='Apelido'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cidade',
            field=models.CharField(blank=True, max_length=60, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cnh',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cnh'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cnh_categoria',
            field=models.CharField(blank=True, choices=[('', '----'), ('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('C', 'C'), ('AC', 'AC'), ('D', 'D'), ('AD', 'AD'), ('E', 'E'), ('AE', 'AE'), ('ACC', 'ACC')], max_length=4, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cnh_emissao',
            field=models.DateField(blank=True, null=True, verbose_name='Emissão'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cnh_primeira_habilitacao',
            field=models.DateField(blank=True, null=True, verbose_name='Primeira Habilitação'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cnh_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Validade'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cpf'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(blank=True, default=datetime.datetime.today, null=True, verbose_name='Data Admissão'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_desligamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data Desligamento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data Nascimento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='detalhe',
            field=models.TextField(blank=True, verbose_name='Detalhe'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.CharField(blank=True, max_length=150, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('S', 'Solteiro'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viuvo')], max_length=3, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.filial', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='fone1',
            field=models.CharField(blank=True, max_length=20, verbose_name='Fone 1'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='fone2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Fone 2'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(blank=True, upload_to='pessoal/fotos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(max_length=15, unique=True, verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='motivo_desligamento',
            field=models.CharField(blank=True, choices=[('EM', 'Pelo Empregador'), ('JC', 'Por Justa Causa'), ('PD', 'Pedido de Desligamento'), ('RI', 'Rescisão Indireta'), ('AB', 'Abandono de Emprego'), ('DJ', 'Descisão Judicial')], max_length=3, verbose_name='Motivo Desligamento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome da Mãe'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome do Pai'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome_social',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome Social'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='pne',
            field=models.BooleanField(default=False, verbose_name='Pne'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='reservista',
            field=models.CharField(blank=True, max_length=20, verbose_name='Reservista'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='rg',
            field=models.CharField(blank=True, max_length=20, verbose_name='Rg'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='rg_emissao',
            field=models.DateField(blank=True, null=True, verbose_name='Rg Emissão'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='rg_orgao_expedidor',
            field=models.CharField(blank=True, max_length=15, verbose_name='Rg Org Expedidor'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Ativo'), ('F', 'Afastado'), ('D', 'Desligado')], default='A', max_length=3, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='titulo_eleitor',
            field=models.CharField(blank=True, max_length=20, verbose_name='Titulo Eleitor'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='titulo_secao',
            field=models.CharField(blank=True, max_length=8, verbose_name='Seção'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='titulo_zona',
            field=models.CharField(blank=True, max_length=10, verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='uf',
            field=models.CharField(blank=True, max_length=5, verbose_name='Uf'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='grupoevento',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='motivoreajuste',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='dias_ciclo',
            field=models.PositiveIntegerField(default=7, verbose_name='Dias Ciclo'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='inicio',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='nome',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='turnodia',
            name='carga_horaria',
            field=models.DurationField(verbose_name='Carga Horária'),
        ),
        migrations.AlterField(
            model_name='turnodia',
            name='eh_folga',
            field=models.BooleanField(default=False, verbose_name='É Folga'),
        ),
        migrations.AlterField(
            model_name='turnodia',
            name='entrada',
            field=models.TimeField(verbose_name='Entrada'),
        ),
        migrations.AlterField(
            model_name='turnodia',
            name='posicao_ciclo',
            field=models.IntegerField(verbose_name='Posição Ciclo'),
        ),
        migrations.AlterField(
            model_name='turnodia',
            name='saida',
            field=models.TimeField(verbose_name='Saída'),
        ),
        migrations.AlterField(
            model_name='turnodia',
            name='tolerancia',
            field=models.PositiveIntegerField(default=10, verbose_name='Tolerância'),
        ),
        migrations.AlterField(
            model_name='turnodia',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='pessoal.turno', verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='turnohistorico',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_turnos', to='pessoal.contrato', verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='turnohistorico',
            name='inicio_vigencia',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Inicio Vigência'),
        ),
        migrations.AlterField(
            model_name='turnohistorico',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoal.turno', verbose_name='Turno'),
        ),
    ]
