# Generated by Django 5.2.7 on 2025-12-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocargo',
            name='valor',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventofuncionario',
            name='valor',
            field=models.TextField(blank=True),
        ),
    ]
