# Generated by Django 6.0.2 on 2026-03-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='carga_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Carga Diária'),
        ),
    ]
