# Generated by Django 5.2.7 on 2025-11-03 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pessoal.grupoevento'),
        ),
    ]
