# Generated by Django 6.0.2 on 2026-03-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0002_alter_contrato_carga_diaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='processamentojob',
            name='progresso',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Progresso'),
        ),
    ]
