# Generated by Django 5.2.7 on 2025-11-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0002_alter_evento_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoevento',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
