# Generated by Django 5.2.7 on 2025-12-12 08:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_log'),
        ('pessoal', '0002_alter_eventocargo_valor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(default=datetime.datetime.today)),
                ('fim', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('V', '<span data-i18n="common.value">Valor</span>'), ('F', '<span data-i18n="common.formula">Formula</span>')], default='V', max_length=3)),
                ('valor', models.TextField(blank=True)),
                ('empresas', models.ManyToManyField(related_name='eventos_empresa', to='core.empresa')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.evento')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.motivoreajuste')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
