# Generated by Django 6.0.2 on 2026-03-07 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0002_alter_frequenciaimport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folhapagamento',
            options={'ordering': ['-competencia', 'contrato__funcionario__matricula'], 'permissions': [('folha_dashboard', 'Can view folha dashboard'), ('importar_escalas', 'Can importar escalas'), ('consolidar_frequencia', 'Can consolidar frequencia'), ('rodar_folha', 'Can rodar folha')], 'verbose_name': 'Folha de Pagamento', 'verbose_name_plural': 'Folhas de Pagamento'},
        ),
    ]
