# Generated by Django 6.0.2 on 2026-02-16 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pessoal', '0002_alter_pessoalsettings_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoalsettings',
            name='filial',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='pessoal_settings', to='core.filial'),
        ),
    ]
