# Generated by Django 5.2.7 on 2025-12-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0002_rename_empresas_eventocargo_filiais_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='funcoes_fixas',
        ),
        migrations.DeleteModel(
            name='FuncaoFixa',
        ),
        migrations.AddField(
            model_name='cargo',
            name='funcoes_fixas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
