# Generated by Django 5.2.7 on 2025-11-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pessoal', '0002_eventocargo_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventocargo',
            name='empresa',
        ),
        migrations.AddField(
            model_name='evento',
            name='empresas',
            field=models.ManyToManyField(related_name='eventos', to='core.empresa'),
        ),
    ]
