# Generated by Django 6.0.2 on 2026-02-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0002_remove_turnodia_entrada_remove_turnodia_saida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='inicia_em',
            field=models.CharField(choices=[('0', 'Domingo'), ('1', 'Segunda'), ('2', 'Terça'), ('3', 'Quarta'), ('4', 'Quinta'), ('5', 'Sexta'), ('6', 'Sábado')], default='0', max_length=1, verbose_name='Inicia em'),
        ),
    ]
