# Generated by Django 5.2.7 on 2025-11-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0002_alter_funcaofixa_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afastamento',
            name='motivo',
            field=models.CharField(blank=True, choices=[('D', '<span data-i18n="personal.common.illness">Doenca</span>'), ('A', '<span data-i18n="personal.employee.form.workplaceAccident">Acidente Trabalho</span>'), ('O', '<span data-i18n="common.other">Outro</span>')], default='D', max_length=3),
        ),
        migrations.AlterField(
            model_name='afastamento',
            name='origem',
            field=models.CharField(blank=True, choices=[('I', 'INSS'), ('E', '<span data-i18n="personal.common.schedule">Escala</span>'), ('S', '<span data-i18n="personal.common.syndicate">Sindicato</span>'), ('G', '<span data-i18n="common.regulator">Gestora</span>'), ('O', '<span data-i18n="common.other">Outro</span>')], default='I', max_length=3),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='parentesco',
            field=models.CharField(blank=True, choices=[('C', '<span data-i18n="personal.common.spouse">Conjuge</span>'), ('F', '<span data-i18n="personal.employee.form.sonStepson">Filho / Enteado</span>'), ('I', '<span data-i18n="personal.common.brother">Irmao</span>'), ('P', '<span data-i18n="personal.employee.form.fatherMother">Pai / Mae</span>'), ('S', '<span data-i18n="personal.common.fatherMotherInLaw">Sogro / Sogra</span>'), ('A', '<span data-i18n="personal.common.ascendant">Ascendente</span>'), ('N', '<span data-i18n="personal.common.descendant">Descendente</span>'), ('In', '<span data-i18n="personal.common.incapable">Incapaz</span>'), ('M', '<span data-i18n="common.other">Outro</span>')], default='F', max_length=3),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('N', '<span data-i18n="compound.notInform">Nao informado</span>'), ('M', '<span data-i18n="common.male">Masculino</span>'), ('F', '<span data-i18n="common.female">Feminino</span>')], max_length=3),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('P', '<span data-i18n="personal.common.profit">Provento</span>'), ('D', '<span data-i18n="personal.common.deduction">Desconto</span>'), ('R', '<span data-i18n="personal.common.reference">Referencia</span>')], default='P', max_length=3),
        ),
        migrations.AlterField(
            model_name='eventocargo',
            name='tipo',
            field=models.CharField(choices=[('V', '<span data-i18n="common.value">Valor</span>'), ('F', '<span data-i18n="common.formula">Formula</span>')], default='V', max_length=3),
        ),
        migrations.AlterField(
            model_name='eventofuncionario',
            name='tipo',
            field=models.CharField(choices=[('V', '<span data-i18n="common.value">Valor</span>'), ('F', '<span data-i18n="common.formula">Formula</span>')], default='V', max_length=3),
        ),
        migrations.AlterField(
            model_name='funcaofixa',
            name='nome',
            field=models.CharField(choices=[('M', '<span data-i18n="personal.common.driver">Motorista</span>'), ('A', '<span data-i18n="personal.common.assistant">Auxiliar</span>'), ('T', '<span data-i18n="personal.common.traffic">Trafego</span>'), ('O', '<span data-i18n="personal.common.mechanics">Oficina</span>')], max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('S', '<span data-i18n="common.single">Solteiro</span>'), ('C', '<span data-i18n="common.married">Casado</span>'), ('D', '<span data-i18n="common.divorced">Divorciado</span>'), ('V', '<span data-i18n="common.widower">Viuvo</span>')], max_length=3),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='motivo_desligamento',
            field=models.CharField(blank=True, choices=[('EM', '<span data-i18n="personal.common.dismissed">Pelo Empregador</span>'), ('JC', '<span data-i18n="personal.employee.form.forJustCause">Por Justa Causa</span>'), ('PD', '<span data-i18n="personal.common.resign">Pedido de Desligamento</span>'), ('RI', '<span data-i18n="personal.employee.form.indirectTermination">Rescisao Indireta</span>'), ('AB', '<span data-i18n="personal.employee.form.abandonment">Abandono de Emprego</span>'), ('DJ', '<span data-i18n="personal.employee.form.judicialTermination">Descisao Judicial</span>')], max_length=3),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='regime',
            field=models.CharField(blank=True, choices=[('CLT', 'CLT'), ('PJ', '<span data-i18n="personal.employee.form.legalEntity">Pessoa Juridica</span>'), ('AP', '<span data-i18n="personal.common.apprentice">Aprendiz</span>')], default='CLT', max_length=5),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('N', '<span data-i18n="compound.notInform">Nao informado</span>'), ('M', '<span data-i18n="common.male">Masculino</span>'), ('F', '<span data-i18n="common.female">Feminino</span>')], max_length=3),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='status',
            field=models.CharField(blank=True, choices=[('A', '<span data-i18n="common.active">Ativo</span>'), ('F', '<span data-i18n="personal.common.onLeave">Afastado</span>'), ('D', '<span data-i18n="personal.common.terminated">Desligado</span>')], default='A', max_length=3),
        ),
    ]
