# Generated by Django 5.2.7 on 2026-02-01 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0002_alter_dependente_funcionario_alter_evento_grupo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventocargo',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='eventoempresa',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='eventofuncionario',
            name='tipo',
        ),
    ]
