# Generated by Django 6.0.2 on 2026-02-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0003_alter_pessoalsettings_filial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventofrequencia',
            name='cor',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Cor Hex'),
        ),
    ]
