# Generated by Django 6.0.2 on 2026-02-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0003_turno_inicia_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnohistorico',
            name='fim_vigencia',
            field=models.DateField(blank=True, null=True, verbose_name='Fim Vigência'),
        ),
        migrations.AlterField(
            model_name='turnodia',
            name='horarios',
            field=models.JSONField(default=list, verbose_name='Horários'),
        ),
    ]
