# Generated by Django 5.2.7 on 2025-11-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pessoal', '0003_remove_eventocargo_empresa_evento_empresas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='empresas',
        ),
        migrations.AddField(
            model_name='eventocargo',
            name='empresas',
            field=models.ManyToManyField(related_name='eventos_cargo', to='core.empresa'),
        ),
    ]
