# Generated by Django 6.0.2 on 2026-03-07 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0003_alter_folhapagamento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rescisao',
            options={'default_permissions': (), 'permissions': [('funcionario_desligar', 'Pode desligar funcionário'), ('funcionario_reativar', 'Pode reativar funcionário')]},
        ),
    ]
