# Generated by Django 5.2.7 on 2025-11-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0003_alter_afastamento_motivo_alter_afastamento_origem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('N', '<span data-i18n="compound.notInformed">Nao informado</span>'), ('M', '<span data-i18n="common.male">Masculino</span>'), ('F', '<span data-i18n="common.female">Feminino</span>')], max_length=3),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('N', '<span data-i18n="compound.notInformed">Nao informado</span>'), ('M', '<span data-i18n="common.male">Masculino</span>'), ('F', '<span data-i18n="common.female">Feminino</span>')], max_length=3),
        ),
    ]
