# Generated by Django 6.0.2 on 2026-03-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0003_processamentojob_progresso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processamentojob',
            name='tipo',
            field=models.CharField(choices=[('CF', 'Consolidação de Frequência'), ('FF', 'Fechamento de Frequência'), ('FP', 'Folha de Pagamento'), ('FH', 'Fechamento de Folha'), ('PF', 'Pagamento de Folha'), ('XF', 'Cancelamento de Folha'), ('CE', 'Carga de Escala')], max_length=2, verbose_name='Tipo'),
        ),
    ]
