# Generated by Django 5.2.7 on 2026-02-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pessoal', '0003_remove_eventocargo_tipo_remove_eventoempresa_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turnohistorico',
            options={'ordering': ['-inicio_vigencia'], 'verbose_name': 'Histórico Turno', 'verbose_name_plural': 'Históricos Turnos'},
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['funcionario', 'inicio', 'fim'], name='idx_contrato_vigencia'),
        ),
        migrations.AddIndex(
            model_name='eventocargo',
            index=models.Index(fields=['cargo', 'inicio', 'fim'], name='idx_ev_cargo_vigencia'),
        ),
        migrations.AddIndex(
            model_name='eventoempresa',
            index=models.Index(fields=['inicio', 'fim'], name='idx_ev_emp_vigencia'),
        ),
        migrations.AddIndex(
            model_name='eventofuncionario',
            index=models.Index(fields=['funcionario', 'inicio', 'fim'], name='idx_ev_func_vigencia'),
        ),
    ]
