# Generated by Django 6.0.2 on 2026-02-15 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_options'),
        ('pessoal', '0004_turnohistorico_fim_vigencia_alter_turnodia_horarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(default=dict)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.filial', verbose_name='Filial')),
            ],
        ),
    ]
