# Generated by Django 6.0.2 on 2026-03-01 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0004_alter_processamentojob_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='frequenciaconsolidada',
            name='fechado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fechado em'),
        ),
        migrations.AddField(
            model_name='frequenciaconsolidada',
            name='fechado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consolidados_fechados', to=settings.AUTH_USER_MODEL, verbose_name='Fechado por'),
        ),
    ]
