# Generated by Django 6.0.2 on 2026-03-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0004_alter_rescisao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescisao',
            name='regras',
            field=models.JSONField(blank=True, default=dict, verbose_name='Memória de Cálculo'),
        ),
        migrations.AddField(
            model_name='rescisao',
            name='total_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Bruto'),
        ),
        migrations.AddField(
            model_name='rescisao',
            name='total_liquido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Líquido'),
        ),
    ]
