# Generated by Django 6.0.2 on 2026-02-08 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0004_alter_turnohistorico_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoFrequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('categoria', models.CharField(choices=[('PRD', 'Jornada/Trabalho'), ('INT', 'Intervalo'), ('AJ', 'Ausência Justificada'), ('ANJ', 'Ausência Não Justificada'), ('HE', 'Hora Extra')], default='PRD', max_length=4, verbose_name='Categoria')),
                ('contabiliza_horas', models.BooleanField(default=True, verbose_name='Contabiliza Horas')),
                ('remunerado', models.BooleanField(default=True, verbose_name='Remunerado')),
                ('dia_inteiro', models.BooleanField(default=False, verbose_name='Dia Inteiro')),
                ('prioridade', models.PositiveIntegerField(default=1, verbose_name='Prioridade')),
                ('cor', models.CharField(default='#3498db', max_length=7, verbose_name='Cor Hex')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, verbose_name='Data')),
                ('inicio', models.TimeField(blank=True, null=True, verbose_name='Início')),
                ('fim', models.TimeField(blank=True, null=True, verbose_name='Fim')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='pessoal.contrato')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoal.eventofrequencia', verbose_name='Evento')),
            ],
            options={
                'ordering': ['data', 'inicio'],
            },
        ),
        migrations.CreateModel(
            name='FolhaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(db_index=True, verbose_name='Competência')),
                ('proventos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Proventos')),
                ('descontos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Descontos')),
                ('liquido', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Líquido')),
                ('regras', models.JSONField(default=dict, verbose_name='Regras')),
                ('erros', models.JSONField(blank=True, null=True, verbose_name='Erros')),
                ('total_erros', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Qtde Erros')),
                ('status', models.CharField(choices=[('R', 'Rascunho'), ('F', 'Fechado'), ('P', 'Pago'), ('C', 'Cancelado')], db_index=True, default='R', max_length=2, verbose_name='Status')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folhas', to='pessoal.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Folha de Pagamento',
                'verbose_name_plural': 'Folhas de Pagamento',
                'ordering': ['-competencia', 'contrato__funcionario__matricula'],
                'unique_together': {('contrato', 'competencia')},
            },
        ),
        migrations.CreateModel(
            name='FrequenciaConsolidada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(db_index=True, verbose_name='Competência')),
                ('inicio', models.DateField(verbose_name='Data Início')),
                ('fim', models.DateField(verbose_name='Data Fim')),
                ('status', models.CharField(choices=[('A', 'Aberto'), ('F', 'Fechado'), ('P', 'Processado')], default='A', max_length=1, verbose_name='Status')),
                ('bloqueado', models.BooleanField(default=False, verbose_name='Bloqueado')),
                ('processamento', models.DateTimeField(blank=True, null=True, verbose_name='Data Processamento')),
                ('consolidado', models.JSONField(blank=True, default=dict, verbose_name='Valores Consolidados')),
                ('erros', models.JSONField(blank=True, default=dict, verbose_name='Logs de Erros')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidados_freq', to='pessoal.contrato')),
            ],
            options={
                'unique_together': {('contrato', 'competencia')},
            },
        ),
    ]
