# Generated by Django 6.0.2 on 2026-02-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0004_alter_eventofrequencia_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='data',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Data'),
        ),
    ]
