# Generated by Django 6.0.2 on 2026-03-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0005_rescisao_regras_rescisao_total_bruto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='cancelado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Cancelado'),
        ),
        migrations.AddField(
            model_name='processamentojob',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='ID do Objeto'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Ativo'), ('F', 'Afastado'), ('D', 'Desligado'), ('PD', 'Desligando...')], db_index=True, default='A', max_length=3, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='processamentojob',
            name='tipo',
            field=models.CharField(choices=[('CF', 'Consolidacao de Frequencia'), ('FF', 'Fechamento de Frequencia'), ('FP', 'Folha de Pagamento'), ('FH', 'Fechamento de Folha'), ('PF', 'Pagamento de Folha'), ('XF', 'Cancelamento de Folha'), ('CE', 'Carga de Escala'), ('DF', 'Desligamento de Funcionário')], max_length=2, verbose_name='Tipo'),
        ),
    ]
