# Generated by Django 6.0.2 on 2026-02-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0005_eventofrequencia_frequencia_folhapagamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnodia',
            name='carga_horaria',
        ),
        migrations.AlterField(
            model_name='turno',
            name='dias_ciclo',
            field=models.PositiveIntegerField(default=0, verbose_name='Dias Ciclo'),
        ),
        migrations.AlterField(
            model_name='turnodia',
            name='entrada',
            field=models.TimeField(blank=True, null=True, verbose_name='Entrada'),
        ),
        migrations.AlterField(
            model_name='turnodia',
            name='saida',
            field=models.TimeField(blank=True, null=True, verbose_name='Saída'),
        ),
    ]
