# Generated by Django 6.0.2 on 2026-02-15 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_options'),
        ('pessoal', '0005_pessoalsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoalsettings',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.filial', unique=True, verbose_name='Filial'),
        ),
    ]
