# Generated by Django 6.0.2 on 2026-02-19 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0005_frequencia_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='inicia_em',
        ),
    ]
