# Generated by Django 6.0.2 on 2026-02-16 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_options'),
        ('pessoal', '0006_alter_pessoalsettings_filial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoalsettings',
            name='filial',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='core.filial', verbose_name='Filial'),
        ),
    ]
