# Generated by Django 6.0.2 on 2026-02-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0006_remove_turnodia_carga_horaria_alter_turno_dias_ciclo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequencia',
            options={'ordering': ['inicio']},
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='data',
        ),
        migrations.AddField(
            model_name='contrato',
            name='carga_mensal',
            field=models.PositiveIntegerField(default=220, verbose_name='Carga Horária Mensal'),
        ),
        migrations.AlterField(
            model_name='frequenciaconsolidada',
            name='fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='frequenciaconsolidada',
            name='inicio',
            field=models.DateTimeField(db_index=True, verbose_name='Início'),
        ),
    ]
