# Generated by Django 6.0.2 on 2026-03-08 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pessoal', '0006_frequencia_cancelado_processamentojob_object_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='processamentojob',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='processamentojob',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'DF'), _negated=True), fields=('tipo', 'filial', 'competencia'), name='unique_job_lote'),
        ),
        migrations.AddConstraint(
            model_name='processamentojob',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'DF')), fields=('tipo', 'object_id'), name='unique_job_objeto'),
        ),
    ]
