# Generated by Django 6.0.2 on 2026-02-23 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pessoal', '0006_remove_turno_inicia_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='carga_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Carga Diária'),
        ),
        migrations.CreateModel(
            name='ProcessamentoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CF', 'Consolidação de Frequência'), ('FP', 'Folha de Pagamento')], max_length=2, verbose_name='Tipo')),
                ('competencia', models.DateField(db_index=True, verbose_name='Competência')),
                ('status', models.CharField(choices=[('AG', 'Aguardando'), ('PR', 'Processando'), ('OK', 'Concluído'), ('ER', 'Erro')], db_index=True, default='AG', max_length=2, verbose_name='Status')),
                ('iniciado_em', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('resultado', models.JSONField(blank=True, default=dict, verbose_name='Resultado')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filial', verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'Job de Processamento',
                'ordering': ['-concluido_em'],
                'unique_together': {('tipo', 'filial', 'competencia')},
            },
        ),
    ]
