# Generated by Django 6.0.2 on 2026-02-08 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0007_alter_frequencia_options_remove_frequencia_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='editado',
            field=models.BooleanField(default=False, verbose_name='Editado Manualmente'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='metadados',
            field=models.JSONField(blank=True, default=dict, help_text='Armazena os horários vindos da FrequenciaImport antes da edição', verbose_name='Importação'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='carga_mensal',
            field=models.PositiveIntegerField(default=220, verbose_name='Carga Mensal'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='inicio',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Início'),
        ),
        migrations.CreateModel(
            name='FrequenciaImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(db_index=True, verbose_name='Data e Hora Original')),
                ('origem', models.CharField(choices=[('AFD', 'Arquivo AFD (Relógio Físico)'), ('APP', 'Aplicativo Móvel (GPS)'), ('WEB', 'Portal do Funcionário'), ('CSV', 'Importação de Planilha')], default='AFD', max_length=3, verbose_name='Origem')),
                ('nsr', models.CharField(blank=True, help_text='Número Sequencial de Registro (AFD)', max_length=50, null=True, verbose_name='NSR')),
                ('num_relogio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Relógio/Equipamento')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('hash_verificacao', models.CharField(blank=True, help_text='Hash de integridade do registro original', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batidas_brutas', to='pessoal.contrato')),
            ],
            options={
                'verbose_name': 'Importação de Frequência',
                'verbose_name_plural': 'Importações de Frequências',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['contrato', 'data_hora'], name='pessoal_fre_contrat_f9b50e_idx')],
            },
        ),
    ]
