# Generated by Django 6.0.2 on 2026-03-08 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0007_alter_processamentojob_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeriasAquisitivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(verbose_name='Início do Período Aquisitivo')),
                ('fim', models.DateField(verbose_name='Fim do Período Aquisitivo')),
                ('inicio_concessivo', models.DateField(verbose_name='Início do Período Concessivo')),
                ('fim_concessivo', models.DateField(verbose_name='Fim do Período Concessivo')),
                ('status', models.CharField(choices=[('AB', 'Em Aquisição'), ('DI', 'Disponível'), ('PA', 'Parcialmente Gozado'), ('GO', 'Gozado'), ('PE', 'Perdido')], db_index=True, default='AB', max_length=2, verbose_name='Status')),
                ('dias_direito', models.PositiveSmallIntegerField(default=30, verbose_name='Dias de Direito')),
                ('regras', models.JSONField(blank=True, default=dict, verbose_name='Memória de Cálculo')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ferias_aquisitivos', to='pessoal.contrato', verbose_name='Contrato')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ferias_aquisitivos', to='pessoal.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Período Aquisitivo de Férias',
                'ordering': ['funcionario', 'inicio'],
            },
        ),
        migrations.CreateModel(
            name='FeriasGozo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(verbose_name='Início do Gozo')),
                ('fim', models.DateField(verbose_name='Fim do Gozo')),
                ('dias', models.PositiveSmallIntegerField(verbose_name='Dias de Gozo')),
                ('abono_pecuniario', models.BooleanField(default=False, verbose_name='Abono Pecuniário')),
                ('dias_abono', models.PositiveSmallIntegerField(default=0, verbose_name='Dias de Abono')),
                ('adiantamento_13', models.BooleanField(default=False, verbose_name='Adiantamento 13º')),
                ('remunerado', models.BooleanField(default=True, verbose_name='Remunerado')),
                ('regras', models.JSONField(blank=True, default=dict, verbose_name='Memória de Cálculo')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('aquisitivo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='gozos', to='pessoal.feriasaquisitivo', verbose_name='Período Aquisitivo')),
            ],
            options={
                'verbose_name': 'Gozo de Férias',
                'ordering': ['aquisitivo', 'inicio'],
            },
        ),
        migrations.AddConstraint(
            model_name='feriasaquisitivo',
            constraint=models.UniqueConstraint(fields=('funcionario', 'inicio'), name='unique_ferias_aquisitivo_por_funcionario'),
        ),
    ]
