# Generated by Django 6.0.2 on 2026-02-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0007_contrato_carga_diaria_processamentojob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folhapagamento',
            options={'ordering': ['-competencia', 'contrato__funcionario__matricula'], 'permissions': [('dashboard', 'Can view dashboard')], 'verbose_name': 'Folha de Pagamento', 'verbose_name_plural': 'Folhas de Pagamento'},
        ),
    ]
