# Generated by Django 6.0.2 on 2026-03-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0008_feriasaquisitivo_feriasgozo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescisao',
            name='data_comunicacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Comunicação'),
        ),
    ]
