# Generated by Django 6.0.2 on 2026-02-25 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0008_alter_folhapagamento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folhapagamento',
            options={'ordering': ['-competencia', 'contrato__funcionario__matricula'], 'permissions': [('folha_dashboard', 'Can view folha dashboard')], 'verbose_name': 'Folha de Pagamento', 'verbose_name_plural': 'Folhas de Pagamento'},
        ),
    ]
