# Generated by Django 6.0.2 on 2026-03-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0009_rescisao_data_comunicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventofrequencia',
            name='categoria',
            field=models.CharField(choices=[('PRD', 'Jornada/Trabalho'), ('INT', 'Intervalo'), ('AJ', 'Ausencia Justificada'), ('ANJ', 'Ausencia Nao Justificada'), ('FLG', 'Folga'), ('HE', 'Hora Extra'), ('FER', 'Feriado')], default='PRD', max_length=4, verbose_name='Categoria'),
        ),
    ]
