# Generated by Django 6.0.2 on 2026-02-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0009_alter_folhapagamento_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processamentojob',
            name='tipo',
            field=models.CharField(choices=[('CF', 'Consolidação de Frequência'), ('FP', 'Folha de Pagamento'), ('CE', 'Carga de Escala')], max_length=2, verbose_name='Tipo'),
        ),
    ]
