# Generated by Django 6.0.2 on 2026-02-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0010_alter_processamentojob_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventofrequencia',
            name='desconta_efetivos',
            field=models.BooleanField(default=False, verbose_name='Desconta dias efetivos'),
        ),
    ]
