# Generated by Django 6.0.2 on 2026-03-10 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0010_alter_eventofrequencia_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['nome'], 'verbose_name': 'Evento'},
        ),
        migrations.AlterField(
            model_name='eventocargo',
            name='fim',
            field=models.DateField(blank=True, null=True, verbose_name='Competência Fim'),
        ),
        migrations.AlterField(
            model_name='eventocargo',
            name='inicio',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Competência Inicio'),
        ),
        migrations.AlterField(
            model_name='eventoempresa',
            name='fim',
            field=models.DateField(blank=True, null=True, verbose_name='Competência Fim'),
        ),
        migrations.AlterField(
            model_name='eventoempresa',
            name='inicio',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Competência Inicio'),
        ),
        migrations.AlterField(
            model_name='eventofuncionario',
            name='fim',
            field=models.DateField(blank=True, null=True, verbose_name='Competência Fim'),
        ),
        migrations.AlterField(
            model_name='eventofuncionario',
            name='inicio',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Competência Inicio'),
        ),
    ]
