# Generated by Django 6.0.2 on 2026-02-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0011_eventofrequencia_desconta_efetivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventofrequencia',
            name='rastreio',
            field=models.SlugField(blank=True, unique=True, verbose_name='Rastreio'),
        ),
    ]
