# Generated by Django 6.0.2 on 2026-03-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0011_alter_evento_options_alter_eventocargo_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependente',
            name='deduz_irrf',
            field=models.BooleanField(default=False, verbose_name='Deduz IRRF'),
        ),
        migrations.AddField(
            model_name='dependente',
            name='deduz_plano_saude',
            field=models.BooleanField(default=False, verbose_name='Deduz Plano de Saúde'),
        ),
        migrations.AddField(
            model_name='dependente',
            name='incapacitado',
            field=models.BooleanField(default=False, verbose_name='Incapacitado'),
        ),
        migrations.AddField(
            model_name='dependente',
            name='plano_saude',
            field=models.BooleanField(default=False, verbose_name='Possui Plano de Saúde'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='parentesco',
            field=models.CharField(blank=True, choices=[('C', 'Conjuge'), ('F', 'Filho / Enteado'), ('I', 'Irmao'), ('P', 'Pai / Mae'), ('S', 'Sogro / Sogra'), ('A', 'Ascendente'), ('N', 'Descendente'), ('M', 'Outro')], default='F', max_length=3, verbose_name='Parentesco'),
        ),
    ]
