# Generated by Django 6.0.2 on 2026-03-11 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0012_dependente_deduz_irrf_dependente_deduz_plano_saude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependente',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dependentes_set', to='pessoal.funcionario', verbose_name='Funcionario'),
        ),
        migrations.CreateModel(
            name='Adiantamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia_pgto', models.DateField()),
                ('competencia_desc', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Cancelado'), ('D', 'Descontado')], default='P', max_length=1)),
                ('observacao', models.TextField(blank=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='adiantamentos', to='pessoal.contrato')),
            ],
            options={
                'ordering': ['-competencia_pgto'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'P')), fields=('contrato', 'competencia_desc'), name='unique_adiantamento_pendente_por_competencia')],
            },
        ),
    ]
