# Generated by Django 6.0.2 on 2026-02-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0012_eventofrequencia_rastreio'),
    ]

    operations = [
        migrations.AddField(
            model_name='processamentojob',
            name='observacoes',
            field=models.JSONField(blank=True, default=list, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='carga_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='C Diária Decimal'),
        ),
    ]
