# Generated by Django 6.0.2 on 2026-03-16 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0013_alter_dependente_funcionario_adiantamento'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='processamentojob',
            name='unique_job_lote',
        ),
        migrations.RemoveConstraint(
            model_name='processamentojob',
            name='unique_job_objeto',
        ),
        migrations.DeleteModel(
            name='ProcessamentoJob',
        ),
    ]
