from django.urls import path
from . import views

urlpatterns = [
    path('pessoal_funcionarios',views.funcionarios,name='pessoal_funcionarios'),
    path('pessoal_funcionario_add',views.funcionario_add,name='pessoal_funcionario_add'),
    path('pessoal_funcionario_id/<int:id>',views.funcionario_id,name='pessoal_funcionario_id'),
    path('pessoal_funcionario_update/<int:id>',views.funcionario_update,name='pessoal_funcionario_update'),
    path('pessoal_funcionario_delete/<int:id>/delete',views.funcionario_delete,name='pessoal_funcionario_delete'),
    path('pessoal_setores',views.setores,name='pessoal_setores'),
    path('pessoal_setor_add',views.setor_add,name='pessoal_setor_add'),
    path('pessoal_setor_id/<int:id>',views.setor_id,name='pessoal_setor_id'),
    path('pessoal_setor_update/<int:id>',views.setor_update,name='pessoal_setor_update'),
    path('pessoal_setor_delete/<int:id>/delete',views.setor_delete,name='pessoal_setor_delete'),
    path('pessoal_cargos',views.cargos,name='pessoal_cargos'),
    path('pessoal_cargo_add',views.cargo_add,name='pessoal_cargo_add'),
    path('pessoal_cargo_id/<int:id>',views.cargo_id,name='pessoal_cargo_id'),
    path('pessoal_cargo_update/<int:id>',views.cargo_update,name='pessoal_cargo_update'),
    path('pessoal_cargo_delete/<int:id>/delete',views.cargo_delete,name='pessoal_cargo_delete'),
    path('pessoal_eventos',views.eventos,name='pessoal_eventos'),
    path('pessoal_evento_add',views.evento_add,name='pessoal_evento_add'),
    path('pessoal_evento_id/<int:id>',views.evento_id,name='pessoal_evento_id'),
    path('pessoal_evento_update/<int:id>',views.evento_update,name='pessoal_evento_update'),
    path('pessoal_evento_delete/<int:id>/delete',views.evento_delete,name='pessoal_evento_delete'),
    path('pessoal_grupos_evento',views.grupos_evento,name='pessoal_grupos_evento'),
    path('pessoal_grupo_evento_add',views.grupo_evento_add,name='pessoal_grupo_evento_add'),
    path('pessoal_grupo_evento_id/<int:id>',views.grupo_evento_id,name='pessoal_grupo_evento_id'),
    path('pessoal_grupo_evento_update/<int:id>',views.grupo_evento_update,name='pessoal_grupo_evento_update'),
    path('pessoal_grupo_evento_delete/<int:id>/delete',views.grupo_evento_delete,name='pessoal_grupo_evento_delete'),
    path('pessoal_get_setores',views.get_setores,name='pessoal_get_setores'),
    path('pessoal_get_cargos',views.get_cargos,name='pessoal_get_cargos'),
    path('pessoal_get_grupos_evento',views.get_grupos_evento,name='pessoal_get_grupos_evento'),
    path('pessoal_add_grupo_evento',views.add_grupo_evento,name='pessoal_add_grupo_evento'),
    # path('pessoal_update_grupo_evento', views.update_grupo_evento,name='pessoal_update_grupo_evento'),
    # path('pessoal_delete_grupo_evento', views.delete_grupo_evento,name='pessoal_delete_grupo_evento'),
]