# Generated by Django 5.2.7 on 2025-12-21 12:58

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('razao_social', models.CharField(blank=True, max_length=150)),
                ('cnpj_base', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_caracteres_senha', models.PositiveIntegerField(default=8)),
                ('senha_exige_alpha', models.BooleanField(default=True)),
                ('senha_exige_numero', models.BooleanField(default=True)),
                ('senha_exige_maiuscula', models.BooleanField(default=False)),
                ('senha_exige_caractere', models.BooleanField(default=False)),
                ('historico_senhas_nao_repetir', models.PositiveIntegerField(default=0)),
                ('quantidade_tentantivas_erradas', models.PositiveIntegerField(default=3)),
            ],
            options={
                'default_permissions': ('view', 'change'),
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=20)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=25)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=25)),
                ('cnae', models.CharField(blank=True, max_length=20)),
                ('atividade', models.CharField(blank=True, max_length=255)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=60)),
                ('uf', models.CharField(blank=True, max_length=5)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('fone', models.CharField(blank=True, max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('logo', core.models.ImageField(blank=True, upload_to='core/logos/')),
                ('footer', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_password_change', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict, null=True)),
                ('filiais', models.ManyToManyField(to='core.filial')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('debug', 'Can debug system'), ('docs', 'Can access system docs')],
                'default_permissions': [],
            },
        ),
    ]
