# Generated by Django 6.0.2 on 2026-03-11 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AG', 'Aguardando'), ('PR', 'Processando'), ('OK', 'Concluído'), ('ER', 'Erro')], db_index=True, default='AG', max_length=2)),
                ('progresso', models.PositiveSmallIntegerField(default=0)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('erros', models.JSONField(blank=True, default=list)),
                ('observacoes', models.JSONField(blank=True, default=list)),
                ('historico', models.JSONField(blank=True, default=list)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['app', 'tipo'], name='core_job_app_759756_idx'), models.Index(fields=['status'], name='core_job_status_4b2344_idx'), models.Index(fields=['criado_em'], name='core_job_criado__96d840_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('arquivo', models.FileField(upload_to='jobs/%Y/%m/')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV'), ('XLSX', 'Excel'), ('ZIP', 'ZIP')], default='PDF', max_length=4)),
                ('tamanho', models.PositiveIntegerField(default=0)),
                ('objeto_id_ref', models.CharField(blank=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('baixado_em', models.DateTimeField(blank=True, null=True)),
                ('impresso_em', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_jobarq_content_f71913_idx'), models.Index(fields=['expira_em'], name='core_jobarq_expira__17aa56_idx')],
            },
        ),
    ]
