# Generated by Django 5.2.7 on 2026-01-24 17:47

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa'},
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj_base',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cnpj Base'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(blank=True, max_length=150, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='atividade',
            field=models.CharField(blank=True, max_length=255, verbose_name='Atividade'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='cep',
            field=models.CharField(blank=True, max_length=10, verbose_name='Cep'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='cidade',
            field=models.CharField(blank=True, max_length=60, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='cnae',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cnae'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cnpj'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filiais', to='core.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='fax',
            field=models.CharField(blank=True, max_length=20, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='fone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Fone'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='footer',
            field=models.TextField(blank=True, verbose_name='Rodapé'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='fuso_horario',
            field=models.CharField(blank=True, choices=core.models.get_timezone_choices, max_length=50, verbose_name='Fuso Horário'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=25, verbose_name='Inscrição Estadual'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=25, verbose_name='Inscrição Municipal'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='logo',
            field=models.ImageField(blank=True, upload_to='core/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='nome',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='uf',
            field=models.CharField(blank=True, max_length=5, verbose_name='Uf'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='config',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Configurações'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='filiais',
            field=models.ManyToManyField(blank=True, to='core.filial', verbose_name='Filiais'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='force_password_change',
            field=models.BooleanField(default=True, verbose_name='Forçar troca de senha'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
