# Generated by Django 5.2.7 on 2025-12-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='filiais',
            field=models.ManyToManyField(blank=True, to='core.filial'),
        ),
    ]
