# Generated by Django 4.2.4 on 2023-09-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='senha_exige_maiuscula',
            field=models.BooleanField(default=False),
        ),
    ]
