# Generated by Django 4.2.4 on 2023-12-18 18:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=60)),
                ('referencia', models.CharField(max_length=60)),
                ('inicio', models.DateTimeField(default=datetime.datetime.now)),
                ('termino', models.DateTimeField(blank=True, null=True)),
                ('erros', models.TextField(blank=True)),
                ('anexo', models.FileField(blank=True, upload_to='core/jobs/')),
                ('status', models.CharField(default='Processando', max_length=60)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': [],
            },
        ),
    ]
