# Generated by Django 5.2.7 on 2026-01-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='fuso_horario',
            field=models.CharField(default='America/Sao_Paulo', max_length=50),
        ),
    ]
