# Generated by Django 5.2.7 on 2026-01-18 11:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_filial_fuso_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='fuso_horario',
            field=models.CharField(blank=True, choices=core.models.get_timezone_choices, default='America/Sao_Paulo', max_length=50),
        ),
    ]
