# Generated by Django 4.2.4 on 2023-12-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='erros',
            field=models.FileField(blank=True, upload_to='core/jobs/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(default='<span class="text-secondary">Processando</span>', max_length=60),
        ),
    ]
