# Generated by Django 5.2.7 on 2025-12-22 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_filiais'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='filial',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filiais', to='core.empresa'),
        ),
    ]
