from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('index',views.index,name='index'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('authenticate',views.authenticate,name='authenticate'),
    path('change_password',views.change_password,name='change_password'),
    path('logs',views.logs,name='logs'),
    path('i18n',views.i18n,name='i18n'),
    path('jobs',views.jobs,name='jobs'),
    path('jobs_download/<int:id>',views.jobs_download,name='jobs_download'),
    path('jobs_clean',views.jobs_clean,name='jobs_clean'),
    path('handler/<int:code>',views.handler,name='handler'),
    path('usuarios',views.usuarios,name='usuarios'),
    path('usuario_add',views.usuario_add,name='usuario_add'),
    path('usuario_id/<int:id>',views.usuario_id,name='usuario_id'),
    path('usuario_update/<int:id>',views.usuario_update,name='usuario_update'),
    path('usuario_delete/<int:id>',views.usuario_delete,name='usuario_delete'),
    path('usuarios_grupo/<int:id>',views.usuarios_grupo,name='usuarios_grupo'),
    path('grupos',views.grupos,name='grupos'),
    path('grupo_add',views.grupo_add,name='grupo_add'),
    path('grupo_id/<int:id>',views.grupo_id,name='grupo_id'),
    path('grupo_update/<int:id>',views.grupo_update,name='grupo_update'),
    path('grupo_delete/<int:id>',views.grupo_delete,name='grupo_delete'),
    path('empresas',views.empresas,name='empresas'),
    path('empresa_add',views.empresa_add,name='empresa_add'),
    path('empresa_id/<int:id>',views.empresa_id,name='empresa_id'),
    path('empresa_update/<int:id>',views.empresa_update,name='empresa_update'),
    path('empresa_delete/<int:id>',views.empresa_delete,name='empresa_delete'),
    path('settings',views.settings,name='settings'),
    path('settings_update/<int:id>',views.settings_update,name='settings_update'),
    path('get_empresas',views.get_empresas,name='get_empresas'),
    path('get_grupos',views.get_grupos,name='get_grupos'),
    path('get_user_perms',views.get_user_perms,name='get_user_perms'),
    path('get_group_perms',views.get_group_perms,name='get_group_perms'),
    path('api/formula_validate',views.formula_validate,name='formula_validate'),
]